---
on:
  workflow_dispatch:
    inputs:
      package_module:
        description: package python module
        required: true
        default: false
        type: boolean

jobs:
  package_rel_candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pip3 install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: Setup python environment
        run: |
          poetry install
      - name: Increment package version
        run: |
          poetry run semantic-release print-version --current
          poetry run semantic-release versiob --noop


