---
on:
  workflow_dispatch:
    inputs:
      package_module:
        description: package python module
        required: true
        default: false
        type: boolean

jobs:
  package_rel_candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: Setup python environment
        run: |
          poetry install
      - name: 
        run: |
          echo "hello"
          python --version
          poetry env list
          poetry install


